server:
  port:8880

logging:
  path:logs
  file:mylog.log
spring:
  application:
    name:mytest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://30.24.149.96:3306/course
    username: root
    password: 123

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
    